[package]
name = "cms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
lazy_static = "1.4.0"
regex = "1.7.1"
tmdb-async = "0.6.2"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
walkdir = "2.3.2"
